from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any, cast

import yaml


ROOT = Path(__file__).resolve().parents[2]
COMMON_DIR = ROOT / "common"
OPENCLAW_DIR = ROOT / "adapters" / "openclaw"
WORKSPACE_DIR = OPENCLAW_DIR / "workspace"
WHITELIST_PATH = COMMON_DIR / "docs" / "migration" / "v0-whitelist.md"

HEADER = "<!-- Generated by tools/projectors/generate_openclaw.py. Do not edit by hand. -->\n"

SHARED_DOC_PATHS = {
    "protocols/collaboration.md": "docs/protocols/collaboration.md",
    "workflows/onboarding.md": "docs/workflows/onboarding.md",
    "workflows/engine-setup.md": "docs/workflows/engine-setup.md",
    "workflows/design-review.md": "docs/workflows/design-review.md",
}
SHARED_DOC_IDS = {
    "collaboration-protocol": "protocols/collaboration.md",
    "onboarding": "workflows/onboarding.md",
    "engine-setup": "workflows/engine-setup.md",
    "design-review-workflow": "workflows/design-review.md",
}


def _load_yaml(path: Path) -> dict[str, Any]:
    return cast(dict[str, Any], yaml.safe_load(path.read_text(encoding="utf-8")))


def _load_manifests(kind: str) -> list[dict[str, Any]]:
    manifest_dir = COMMON_DIR / "manifests" / kind
    return [_load_yaml(path) for path in sorted(manifest_dir.glob("*.yaml"))]


def _parse_whitelist() -> dict[str, list[str]]:
    included: dict[str, list[str]] = {
        "agents": [],
        "skills": [],
        "shared docs": [],
        "policies": [],
        "workflows": [],
    }
    current_h2 = ""
    current_h3 = ""

    for raw_line in WHITELIST_PATH.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if line.startswith("## "):
            current_h2 = line[3:].strip()
            current_h3 = ""
            continue
        if line.startswith("### "):
            current_h3 = line[4:].strip()
            continue
        if not line.startswith("- `") or not line.endswith("`"):
            continue

        item = line[3:-1]
        if (
            current_h2 == "Included v0 artifacts (authoritative)"
            and current_h3 in included
        ):
            included[current_h3].append(item)

    return {
        "agents": included["agents"],
        "skills": included["skills"],
        "shared docs": included["shared docs"],
        "policies": included["policies"],
        "workflows": included["workflows"],
    }


def _load_openclaw_platform() -> dict[str, Any]:
    feature_matrix = _load_yaml(COMMON_DIR / "compatibility" / "feature-matrix.yaml")
    platforms = cast(list[dict[str, Any]], feature_matrix["platforms"])
    for platform in platforms:
        if platform["id"] == "openclaw":
            return platform
    raise RuntimeError("OpenClaw compatibility entry not found")


def _load_warning_map() -> dict[str, dict[str, Any]]:
    warning_taxonomy = _load_yaml(
        COMMON_DIR / "compatibility" / "warning-taxonomy.yaml"
    )
    warnings = cast(list[dict[str, Any]], warning_taxonomy["warnings"])
    return {cast(str, warning["code"]): warning for warning in warnings}


def _load_openclaw_hazards() -> list[dict[str, Any]]:
    workaround_matrix = _load_yaml(
        COMMON_DIR / "compatibility" / "workaround-matrix.yaml"
    )
    hazards = cast(list[dict[str, Any]], workaround_matrix["hazard_workarounds"])
    return [
        hazard
        for hazard in hazards
        if "openclaw" in cast(list[str], hazard["applies_to"])
    ]


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _bullet_list(items: list[str], indent: str = "") -> str:
    return "\n".join(f"{indent}- {item}" for item in items)


def _render_agents_index(agents: list[dict[str, Any]]) -> str:
    lines = [HEADER.rstrip(), "# OpenClaw Agent Index", "", "## Support posture", ""]
    lines.extend(
        [
            "- OpenClaw v0 is projected for repository and CLI usage only.",
            "- Gateway or channel-native runtime parity is explicitly out of scope.",
            "- Approval gates and validation hooks are surfaced through external-runner metadata instead of native runtime interception.",
            "",
            "## Available agents",
            "",
        ]
    )
    for agent in agents:
        agent_id = cast(str, agent["id"])
        title = cast(str, agent["title"])
        purpose = cast(str, agent["purpose"])
        lines.append(f"- `{title}` (`agents/{agent_id}.md`) — {purpose}")
    lines.extend(
        [
            "",
            "## Workspace entrypoints",
            "",
            "- `SOUL.md` explains the repo-level operating contract and fallback boundaries.",
            "- `skills/*/SKILL.md` preserves skill packaging for CLI invocation and repository browsing.",
        ]
    )
    return "\n".join(lines) + "\n"


def _render_soul(
    platform: dict[str, Any],
    warnings: dict[str, dict[str, Any]],
    hazards: list[dict[str, Any]],
) -> str:
    feature_lines = []
    for feature in cast(list[dict[str, Any]], platform["features"]):
        feature_lines.append(
            "- "
            f"`{feature['feature_id']}` -> support `{feature['support']}` via "
            f"`{feature['workaround_class']}`"
        )

    hazard_lines = []
    for hazard in hazards:
        warning_code = cast(str, hazard["warning_code"])
        warning = warnings[warning_code]
        hazard_lines.append(
            "- "
            f"`{cast(str, hazard['canonical_feature'])}`: {cast(str, hazard['recommended_fallback'])} "
            f"({warning_code}, severity {cast(str, warning['severity'])})"
        )

    lines = [
        HEADER.rstrip(),
        "# OpenClaw SOUL",
        "",
        "## Core contract",
        "",
        "- Deliver a repository-readable and CLI-usable workspace for the whitelisted v0 slice.",
        "- Do not claim or emulate gateway-native or channel-native runtime behavior.",
        "- Route unsupported semantics through wrapper metadata or external runners instead of force-fitting them into fake native hooks.",
        "",
        "## Support level",
        "",
        f"- Posture: `{cast(str, platform['posture'])}`",
        "- Native parity: not supported in v0",
        "- Supported surfaces: repository layout, markdown packaging, CLI-driven task entrypoints",
        "- Unsupported surfaces: gateway integrations, channel-native UI, runtime hook parity",
        "",
        "## Projected feature handling",
        "",
        *feature_lines,
        "",
        "## Approved OpenClaw fallbacks",
        "",
        *hazard_lines,
        "",
        "## External-runner boundary",
        "",
        "- Policy guards remain explicit metadata for an external validator or wrapper script.",
        "- Workflow approval gates remain documented checkpoints; the CLI should stop and wait for user confirmation before writes.",
    ]
    return "\n".join(lines) + "\n"


def _render_agent(agent: dict[str, Any]) -> str:
    capabilities = _bullet_list(cast(list[str], agent["capabilities"]))
    tools = _bullet_list(cast(list[str], agent["tool_capability_needs"]))
    projection_notes = [
        note
        for note in cast(list[dict[str, Any]], agent["projection_notes"])
        if note["target"] == "openclaw"
    ]
    warnings = _bullet_list(
        [
            f"`{cast(str, rule['code'])}`: {cast(str, rule['recommended_fallback'])}"
            for rule in cast(list[dict[str, Any]], agent["warning_rules"])
        ]
    )
    note_lines = _bullet_list(
        [
            f"{cast(str, note['note'])} (workaround `{cast(str, note['workaround_class'])}`)"
            for note in projection_notes
        ]
    )
    return (
        f"{HEADER}# {cast(str, agent['title'])}\n\n"
        f"- Agent id: `{cast(str, agent['id'])}`\n"
        f"- Model profile: `{cast(str, agent['model_profile'])}`\n"
        f"- Delegation intent: `{cast(str, agent['delegation_intent'])}`\n"
        f"- Collaboration contract: `{cast(str, agent['collaboration_contract_ref'])}`\n\n"
        f"## Purpose\n\n{cast(str, agent['purpose'])}\n\n"
        f"## Capabilities\n\n{capabilities}\n\n"
        f"## Tool capability needs\n\n{tools}\n\n"
        f"## OpenClaw fallback notes\n\n{note_lines}\n\n"
        f"## Warning rules\n\n{warnings}\n"
    )


def _render_skill(skill: dict[str, Any]) -> str:
    inputs = _bullet_list(cast(list[str], skill["required_inputs"]))
    capabilities = _bullet_list(cast(list[str], skill["required_capabilities"]))
    outputs = _bullet_list(cast(list[str], skill["outputs"]))
    steps = _bullet_list(
        [
            f"`{cast(str, step['step_id'])}` — {cast(str, step['intent'])} "
            f"(confirmation: {cast(bool, step['requires_confirmation'])})"
            for step in cast(list[dict[str, Any]], skill["workflow_steps"])
        ]
    )
    rules = _bullet_list(
        [
            f"`{cast(str, rule['warning_code'])}` via `{cast(str, rule['workaround_class'])}` "
            f"for `{cast(str, rule['hazard_category'])}`"
            for rule in cast(list[dict[str, Any]], skill["workaround_rules"])
        ]
    )
    projection_notes = [
        note
        for note in cast(list[dict[str, Any]], skill["projection_notes"])
        if note["target"] == "openclaw"
    ]
    note_lines = _bullet_list(
        [
            f"{cast(str, note['note'])} (workaround `{cast(str, note['workaround_class'])}`)"
            for note in projection_notes
        ]
    )
    return (
        f"{HEADER}# {cast(str, skill['id'])}\n\n"
        f"- User entrypoint: `{cast(str, skill['user_entrypoint'])}`\n"
        f"- Interactive capture mode: `{cast(str, skill['interactive_capture_mode'])}`\n\n"
        f"## Intent\n\n{cast(str, skill['intent']).strip()}\n\n"
        f"## Required inputs\n\n{inputs}\n\n"
        f"## Workflow steps\n\n{steps}\n\n"
        f"## Required capabilities\n\n{capabilities}\n\n"
        f"## Outputs\n\n{outputs}\n\n"
        f"## OpenClaw fallback notes\n\n{note_lines}\n\n"
        f"## Compatibility warnings\n\n{rules}\n"
    )


def _render_policy(policy: dict[str, Any]) -> str:
    rule_lines = _bullet_list(
        [
            f"`{cast(str, rule['code'])}` ({cast(str, rule['severity'])}/{cast(str, rule['failure_mode'])}) — {cast(str, rule['statement']).strip()}"
            for rule in cast(list[dict[str, Any]], policy["rules"])
        ]
    )
    return (
        f"{HEADER}# {cast(str, policy['title'])}\n\n"
        f"- Policy id: `{cast(str, policy['id'])}`\n"
        f"- Enforcement level: `{cast(str, cast(dict[str, Any], policy['enforcement'])['level'])}`\n"
        "- OpenClaw handling: external runner metadata; no native hook parity in v0\n\n"
        f"## Rules\n\n{rule_lines}\n"
    )


def _render_workflow(workflow: dict[str, Any]) -> str:
    stage_lines = _bullet_list(
        [
            f"`{cast(str, stage['stage_id'])}` ({cast(str, stage['actor'])}) -> approval gate `{cast(str, stage['approval_gate'])}` using fallback `{cast(str, stage['fallback_strategy'])}`"
            for stage in cast(list[dict[str, Any]], workflow["stages"])
        ]
    )
    invariants = _bullet_list(
        [
            f"`{key}` = {str(value).lower()}"
            for key, value in sorted(
                cast(dict[str, Any], workflow["invariants"]).items()
            )
        ]
    )
    return (
        f"{HEADER}# {cast(str, workflow['id'])}\n\n"
        f"{cast(str, workflow['summary'])}\n\n"
        "## OpenClaw handling\n\n"
        "- Approval remains explicit before any write operation.\n"
        "- The runtime surface is CLI-only, so approval checkpoints are documented and must be executed by a wrapper or operator.\n"
        "- No gateway or channel-native approval widgets are implied.\n\n"
        f"## Stages\n\n{stage_lines}\n\n"
        f"## Invariants\n\n{invariants}\n"
    )


def _render_config(
    platform: dict[str, Any],
    hazards: list[dict[str, Any]],
    agents: list[dict[str, Any]],
    skills: list[dict[str, Any]],
    policies: list[dict[str, Any]],
    workflows: list[dict[str, Any]],
) -> str:
    warnings = sorted({cast(str, hazard["warning_code"]) for hazard in hazards})
    config = {
        "schema_version": "1.0",
        "platform": "openclaw",
        "support_posture": cast(str, platform["posture"]),
        "native_parity": "not_supported_in_v0",
        "workspace_root": "workspace",
        "workspace_entrypoints": {
            "agents_index": "workspace/AGENTS.md",
            "soul": "workspace/SOUL.md",
        },
        "supported_surfaces": ["repository_layout", "cli_invocation"],
        "unsupported_surfaces": [
            "gateway_integration",
            "channel_native_runtime",
            "runtime_hook_parity",
        ],
        "features": cast(list[dict[str, Any]], platform["features"]),
        "fallback_contract": {
            "interactive_capture": "generated_wrapper_or_explicit_cli_prompts",
            "slash_invocation": "explicit_command_or_task_entrypoint",
            "delegation": "single_step_or_staged_cli_checkpoint",
            "policy_guards": "external_runner_metadata",
            "workflow_approval_gates": "external_runner_metadata",
        },
        "external_runner": {
            "policies": [cast(str, policy["id"]) for policy in policies],
            "workflows": [cast(str, workflow["id"]) for workflow in workflows],
        },
        "workspace_inventory": {
            "agents": [
                f"workspace/agents/{cast(str, agent['id'])}.md" for agent in agents
            ],
            "skills": [
                f"workspace/skills/{cast(str, skill['id'])}/SKILL.md"
                for skill in skills
            ],
            "policies": [
                f"workspace/policies/{cast(str, policy['id'])}.md"
                for policy in policies
            ],
            "workflows": [
                f"workspace/workflows/{cast(str, workflow['id'])}.md"
                for workflow in workflows
            ],
            "docs": [f"workspace/{target}" for target in SHARED_DOC_PATHS.values()],
        },
        "warning_codes": warnings,
    }
    return json.dumps(config, indent=2, sort_keys=True) + "\n"


def generate() -> list[Path]:
    whitelist = _parse_whitelist()
    agent_ids = set(whitelist["agents"])
    skill_ids = set(whitelist["skills"])
    shared_doc_ids = set(whitelist["shared docs"])
    policy_ids = set(whitelist["policies"])
    workflow_ids = set(whitelist["workflows"])
    agents = [
        agent
        for agent in _load_manifests("agents")
        if cast(str, agent["id"]) in agent_ids
    ]
    skills = [
        skill
        for skill in _load_manifests("skills")
        if cast(str, skill["id"]) in skill_ids
    ]
    policies = [
        policy
        for policy in _load_manifests("policies")
        if cast(str, policy["id"]) in policy_ids
    ]
    workflows = [
        workflow
        for workflow in _load_manifests("workflows")
        if cast(str, workflow["id"]) in workflow_ids
    ]
    platform = _load_openclaw_platform()
    warning_map = _load_warning_map()
    hazards = _load_openclaw_hazards()

    if WORKSPACE_DIR.exists():
        shutil.rmtree(WORKSPACE_DIR)
    WORKSPACE_DIR.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []

    def write(relative_path: str, text: str) -> None:
        path = WORKSPACE_DIR / relative_path
        _write_text(path, text)
        written.append(path)

    write("AGENTS.md", _render_agents_index(agents))
    write("SOUL.md", _render_soul(platform, warning_map, hazards))

    for agent in agents:
        write(f"agents/{cast(str, agent['id'])}.md", _render_agent(agent))

    for skill in skills:
        write(f"skills/{cast(str, skill['id'])}/SKILL.md", _render_skill(skill))

    for policy in policies:
        write(f"policies/{cast(str, policy['id'])}.md", _render_policy(policy))

    for workflow in workflows:
        write(
            f"workflows/{cast(str, workflow['id'])}.md",
            _render_workflow(workflow),
        )

    for doc_id in sorted(shared_doc_ids):
        source = SHARED_DOC_IDS[doc_id]
        target = SHARED_DOC_PATHS[source]
        source_path = COMMON_DIR / "docs" / source
        target_path = WORKSPACE_DIR / target
        _write_text(target_path, HEADER + source_path.read_text(encoding="utf-8"))
        written.append(target_path)

    config_path = OPENCLAW_DIR / "openclaw.json5"
    _write_text(
        config_path,
        _render_config(platform, hazards, agents, skills, policies, workflows),
    )
    written.append(config_path)

    return sorted(written)


def main() -> int:
    written = generate()
    for path in written:
        print(path.relative_to(ROOT).as_posix())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
